# Generated by Django 5.0.7 on 2024-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='nomination_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
