# Generated by Django 5.0.7 on 2024-07-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_nomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='api.category'),
        ),
    ]
