# Generated by Django 5.0.7 on 2024-11-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nomination_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='weight',
            new_name='order',
        ),
    ]
