# Generated by Django 5.0.7 on 2024-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_nomination_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('first_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('personal_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
