name: Build frontend
run-name: Building the frontend files
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and execute commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            cd ./minister-awards/frontend
            git pull

            npm install
            npx vite build --outDir /var/www/minister-awards/dist
